### ISSUE TITLE
CI: scripts don't exit on failures if iostats are running in the background

### ISSUE THREAD

**Issue by jrusz** [osbuild/osbuild-composer#2167]
I noticed jobs to hang on errors like here: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1939510174 and figured out it's caused by the iostats running in the background.  I found `mockbuild.sh` failing here: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1939453812 and not exiting so I tried to reproduce it but removed the iostats scripts here: https://github.com/osbuild/osbuild-composer/pull/2165 and the job failed immediately on error as it should: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1940285938

We have to integrate this in a way that this is killed on exit properly like sourcing it from the main scripts being ran in CI and the killing it with a trap could work... I believe this script is being sourced in all the scripts we run in CI so maybe we can integrate it there: https://github.com/osbuild/osbuild-composer/blob/main/tools/set-env-variables.sh 

Another option would be to just remove this, not sure what is it being used for currently though. Either way this can happen in any job not just the mockbuild and then it's just waiting for the job to timeout which is just wasting CI resources.

**Comment by ondrejbudai** [comment]
Fixed I think.

**Comment by jrusz** [comment]
Yes it's removed. I still have a backup branch locally but idk if we want to re-enable it any time soon. I suppose it's not missing.
